before_install: 
- cd ./Server
- ls

language: csharp
solution: ./Server/KomuWDrogeTemuCzasServer.sln

jobs:
  include:
    - dotnet: 2.1.502
      mono: none
    - mono: latest

install:
  - nuget restore ./Server/KomuWDrogeTemuCzasServer.sln
  - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner

script:
  - msbuild /p:Configuration=Release ./Server/KomuWDrogeTemuCzasServer.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./Server/KomuWDrogeTemuCzasTests/bin/Release/KomuWDrogeTemuCzasTests.dll