before_install:
- cd Server

language: csharp
solution: ./KomuWDrogeTemuCzasServer.sln
mono: none
dotnet: 3.1

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test UnitTests/Tests.csproj